FROM ubuntu:latest

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server
RUN service ssh restart

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y sudo
RUN useradd -m {user} -p $(openssl passwd {password})
RUN usermod -aG sudo {user}

RUN apt update && apt install tzdata -y
ENV TZ="America/Chicago"

RUN DEBIAN_FRONTEND=noninteractive \ 
  apt-get install build-essential software-properties-common -y \
  && add-apt-repository ppa:deadsnakes/ppa

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python3.12 \
  && apt-get install -y python3.12-venv \
  && apt-get install -y net-tools \
  && apt-get install -y inetutils-ping

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise, the user is kicked off after login.

RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

EXPOSE 22

RUN python3.12 -m venv /home/tonio/ansible_env \
  && . /home/tonio/ansible_env/bin/activate \
  && pip install --upgrade pip \
  && pip install ansible \ 
  && pip install ansible-lint \
  && deactivate
  
CMD service ssh start ; bash
