FROM ubuntu:latest

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server
RUN service ssh restart

RUN useradd -m {user} -p $(openssl passwd {password})
RUN usermod -aG sudo {user}

RUN apt update && apt install tzdata -y
ENV TZ="America/çhicago"

RUN DEBIAN_FRONTEND=noninteractive \ 
  apt-get install build-essential software-properties-common -y \
  && add-apt-repository ppa:deadsnakes/ppa

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python3.12 \
  && apt-get install -y net-tools \
  && apt-get install -y netutils-ping

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise, the user is kicked off after login.

RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

EXPOSE 22

CMD service ssh start ; bash 
